# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NewStart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewStart

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'Masonry'

  pod 'ReactiveCocoa', '~> 2.5'

end
